# Generated by Django 4.1.2 on 2022-10-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options_article_related_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', upload_to='article-thumbnails', verbose_name='تصویر'),
        ),
    ]
